# Generated by Django 6.0.3 on 2026-03-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcontent',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
