# Generated by Django 6.0.3 on 2026-03-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_uploadedcontent_rating_uploadedcontent_total_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcontent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
