# Generated by Django 6.0.3 on 2026-03-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uploadedcontent_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcontent',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
