# Generated by Django 6.0.3 on 2026-04-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_uploadedcontent_downloads'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
